<a href="https://colab.research.google.com/github/DayrisRM/VisionArtificial-M0T/blob/master/SIFT_with_OpenCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np
import cv2

In [47]:
# Create detector to compute SIFT
detector = cv2.xfeatures2d.SIFT_create()

In [111]:
# Read image and convert to grayscale
imageNameModelo = 'Ex2-Dataset1\\Modelo.png'
imaModelo=cv2.imread(imageNameModelo)

In [112]:
# Detect keypoints with SIFT and sort them according to their response
import time
print ('Extracting Keypoints')
init=time.time()
kpts=detector.detect(imaModelo)

Extracting Keypoints


In [113]:
end=time.time()
print ('Extracted '+str(len(kpts))+' keypoints.')
print ('Done in '+str(end-init)+' secs.')
print ('')

Extracted 482 keypoints.
Done in 0.9707131385803223 secs.



In [91]:
# Compute SIFT descriptor for all keypoints
print ('Computing SIFT descriptors')
init=time.time()
kpts,des=detector.compute(imaModelo,kpts)
end=time.time()
print ('Done in '+str(end-init)+' secs.')
print('des: ' + str(des))

Computing SIFT descriptors
Done in 0.05499696731567383 secs.
des: [[  0.   0.   0. ...   0.   4.   6.]
 [  0.   0.   2. ...   0.   0.   3.]
 [ 21.  29.  14. ...   0.   0.   0.]
 ...
 [  1.   2.   3. ...   0.  46.  36.]
 [  0.  52. 114. ...   0.   0.   6.]
 [  5.  34.   3. ...   0.   1.   7.]]


In [92]:
img=cv2.drawKeypoints(imaModelo,kpts,imaModelo,flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv2.imwrite('Ex2-Dataset1\\sift_t7_keypoints.png',imaModelo)
cv2.imshow('image',imaModelo)