<a href="https://colab.research.google.com/github/DayrisRM/VisionArtificial-M0T/blob/master/SIFT_with_OpenCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import cv2

In [2]:
# Read image and convert to grayscale
imageName = 'bcn-001.jpg'
ima=cv2.imread(imageName)
gray=cv2.cvtColor(ima,cv2.COLOR_BGR2GRAY)

In [3]:
print(cv2.__version__)

3.4.2


In [4]:
# Create detector to compute SIFT
detector = cv2.xfeatures2d.SIFT_create()

In [5]:
# Detect keypoints with SIFT and sort them according to their response
import time
print ('Extracting Keypoints')
init=time.time()
kpts=detector.detect(gray)

Extracting Keypoints


In [6]:
end=time.time()
print ('Extracted '+str(len(kpts))+' keypoints.')
print ('Done in '+str(end-init)+' secs.')
print ('')

Extracted 3585 keypoints.
Done in 1.4166135787963867 secs.



In [15]:
# Compute SIFT descriptor for all keypoints
print ('Computing SIFT descriptors')
init=time.time()
kpts,des=detector.compute(gray,kpts)
end=time.time()
print ('Done in '+str(end-init)+' secs.')
print('des: ' + str(des))

Computing SIFT descriptors
Done in 0.15816807746887207 secs.
des: [[ 0.  0.  3. ...  5. 33. 20.]
 [ 1.  0.  2. ...  8.  3.  7.]
 [94.  7.  7. ... 84. 27.  8.]
 ...
 [ 6. 27. 83. ...  0.  0.  0.]
 [ 0.  0.  0. ... 11.  0.  0.]
 [ 0.  0.  0. ...  0.  1.  1.]]


In [16]:
img=cv2.drawKeypoints(gray,kpts,ima,flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv2.imwrite('sift_keypoints.jpg',img)
cv2.imshow('image',img)